### ISSUE TITLE
luna not available for R v.4.0.5

### ISSUE THREAD

**Issue by ramonmelser** [rspatial/luna#18]
I'm trying to install the luna package, but am receiving an error stating it is not available for my version of R. 
Will it be updated for new versions of R?

**Comment by rhijmans** [comment]
`luna` is not on CRAN. You can install it like this:

```
install.packages('luna', repos='https://rspatial.r-universe.dev')
```

Or like this:

```
remotes::install_github("rspatial/luna")
```
