### ISSUE TITLE
New .cmr_download error and inability to read the downloaded file

### ISSUE THREAD

**Issue by gavi0065** [rspatial/luna#21]
Hi there,

I'm using luna to pull MODIS data. I had a getModis() script that worked as expected yesterday, but today I'm getting the following errors:

In .cmr_download(urls, path, username, password, overwrite) :
  failure: https://e4ftl01.cr.usgs.gov//DP106/MOLT/MOD13Q1.006/2010.06.26/MOD13Q1.A2010177.h11v04.006.2015208204334.hdf

2: In .cmr_download(urls, path, username, password, overwrite) :
  failure: https://e4ftl01.cr.usgs.gov//DP136/MOLT/MOD13Q1.061/2010.06.26/MOD13Q1.A2010177.h11v04.061.2021168170216.hdf

Two files do download to the expected location, but now when i try to turn the files into raster objects using the rast() function from the terra package, I get a new error:

Error: [rast] cannot open file: /Users/ryan/Desktop/untitled folder/MOD13Q1.A2010177.h11v04.061.2021168170216.hdf
In addition: Warning message:
`/Users/jim/Desktop/untitled folder/MOD13Q1.A2010177.h11v04.061.2021168170216.hdf' not recognized as a supported file format. (GDAL error 4) 

Is this a common suite of errors?  I'm trying to figure out if the download error is coming from a bug in luna or a problem with the download site.  I haven't changed the code, so I don't think I've messed something up on my end, but that's entirely possible. Is there a dependency I'm forgetting to load other than luna and terra?

Thanks for your time.

**Comment by JulianneMeisnerUW** [comment]
The exact same thing is happening to me! Did you find a solution to your problem?

**Comment by gavi0065** [comment]
No.  I ended up just accessing the data directly through the Earth Data Cloud python API and processing it in python.  If you're committed to an R solution, the MODIStsp package might be useful, depending on what you're trying to get at. That's where I would have headed next at least.
