### ISSUE TITLE
R not installing luna

### ISSUE THREAD

**Issue by carolkimani** [rspatial/luna#23]
Hi, 

I am trying to install luna on R but I keep getting this error:

`Downloading GitHub repo rspatial/luna@HEAD
√  checking for file 'C:\Users\admin\AppData\Local\Temp\RtmpoH5VLt\remotes25e81737276d\rspatial-luna-66da15b/DESCRIPTION' (821ms)
-  preparing 'luna': (856ms)
√  checking DESCRIPTION meta-information ...
-  cleaning src
-  installing the package to process help pages
         -----------------------------------
-  installing *source* package 'luna' ...
   ** using staged installation
   ** libs
   "C:/rtools40/mingw64/bin/"g++  -std=gnu++11 -I"F:/Folders/Programs/R-4.1.2/include" -DNDEBUG          -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -Wall -pedantic -fdiagnostics-color=always -c modisbits.cpp -o modisbits.o
   C:/rtools40/mingw64/bin/g++ -shared -s -static-libgcc -o luna.dll tmp.def modisbits.o -LF:/Folders/Programs/R-4.1.2/bin/x64 -lR
   installing to C:/Users/admin/AppData/Local/Temp/RtmpAbdlqb/Rinst466c5f3713ce/00LOCK-luna/00new/luna/libs/x64
   ** R
   ** inst
   ** byte-compile and prepare package for lazy loading
   Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
     namespace 'terra' 1.4-22 is being loaded, but >= 1.5.3 is required
   Calls: <Anonymous> ... withCallingHandlers -> loadNamespace -> namespaceImport -> loadNamespace
   Execution halted
   ERROR: lazy loading failed for package 'luna'
-  removing 'C:/Users/admin/AppData/Local/Temp/RtmpAbdlqb/Rinst466c5f3713ce/luna'
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'luna' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout & stderr were printed`

Session Info:

`> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_Kenya.1252  LC_CTYPE=English_Kenya.1252    LC_MONETARY=English_Kenya.1252
[4] LC_NUMERIC=C                   LC_TIME=English_Kenya.1252    

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] fasterize_1.0.3   doParallel_1.0.16 iterators_1.0.13  foreach_1.5.1     tmaptools_3.1-1  
 [6] maditr_0.8.2      geodata_0.3-5     terra_1.4-22      tmap_3.3-2        basf_0.2.0       
[11] sf_1.0-5          data.table_1.14.2 pacman_0.5.1     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7         lattice_0.20-45    prettyunits_1.1.1  ps_1.6.0           png_0.1-7         
 [6] class_7.3-19       rprojroot_2.0.2    digest_0.6.29      utf8_1.2.2         V8_3.6.0          
[11] R6_2.5.1           e1071_1.7-9        ggplot2_3.3.5      pillar_1.6.4       rlang_0.4.12      
[16] curl_4.3.2         geojsonlint_0.4.0  callr_3.7.0        raster_3.5-9       htmlwidgets_1.5.4 
[21] munsell_0.5.0      proxy_0.4-26       compiler_4.1.2     rmapshaper_0.4.5   pkgconfig_2.0.3   
[26] base64enc_0.1-3    pkgbuild_1.3.1     htmltools_0.5.2    tibble_3.1.6       httpcode_0.3.0    
[31] codetools_0.2-18   XML_3.99-0.8       jsonvalidate_1.3.2 fansi_0.5.0        viridisLite_0.4.0 
[36] withr_2.4.3        crayon_1.4.2       crul_1.2.0         grid_4.1.2         jsonlite_1.7.2    
[41] lwgeom_0.2-8       gtable_0.3.0       lifecycle_1.0.1    DBI_1.1.2          magrittr_2.0.1    
[46] units_0.7-2        scales_1.1.1       KernSmooth_2.23-20 cli_3.1.0          leafsync_0.1.0    
[51] remotes_2.4.2      leaflet_2.0.4.1    sp_1.4-6           ellipsis_0.3.2     vctrs_0.3.8       
[56] RColorBrewer_1.1-2 tools_4.1.2        dichromat_2.0-0    leafem_0.1.6       glue_1.6.0        
[61] crosstalk_1.2.0    processx_3.5.2     abind_1.4-5        fastmap_1.1.0      colorspace_2.0-2  
[66] stars_0.5-5        classInt_0.4-3    `

Kindly assist. Thanks

**Comment by rhijmans** [comment]
The error message you get is:

```
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
namespace 'terra' 1.4-22 is being loaded, but >= 1.5.3 is required
```

CRAN has `terra 1.4-22`, so you need to install the development version to get the required version. That is easy to with this command: `install.packages('terra', repos='https://rspatial.r-universe.dev')`

**Comment by carolkimani** [comment]
Hi rhijmans.

Thank you I have installed terra. I am trying to run this command 

`pacman::p_load_gh("rspatial/luna")`

But it still says
 
'Failed to install/load:
rspatial/luna'

Do you know how I can proceed?

**Comment by rhijmans** [comment]
Were you able to install `luna` (*after* installing `terra`)?  This can also be pacman related, I do not know how that works.

**Comment by carolkimani** [comment]
No, I still can't install luna even without the pacman code.

**Comment by rhijmans** [comment]
But can you do it without pacman? And if not, please show the full output you are getting, like in your initial post.

**Comment by carolkimani** [comment]
So these are the command lines I've used"

`install.packages('terra', repos='https://rspatial.r-universe.dev')
remotes::install_github("rspatial/luna")
`

The error:
`Downloading GitHub repo rspatial/luna@HEAD
√  checking for file 'C:\Users\admin\AppData\Local\Temp\RtmpuU4ooe\remotes29882e5b2198\rspatial-luna-66da15b/DESCRIPTION' (432ms)
-  preparing 'luna':
√  checking DESCRIPTION meta-information ...
-  cleaning src
-  installing the package to process help pages
         -----------------------------------
-  installing *source* package 'luna' ...
   ** using staged installation
   ** libs
   "C:/rtools40/mingw64/bin/"g++  -std=gnu++11 -I"F:/Folders/Programs/R-4.1.2/include" -DNDEBUG          -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -Wall -pedantic -fdiagnostics-color=always -c modisbits.cpp -o modisbits.o
   C:/rtools40/mingw64/bin/g++ -shared -s -static-libgcc -o luna.dll tmp.def modisbits.o -LF:/Folders/Programs/R-4.1.2/bin/x64 -lR
   installing to C:/Users/admin/AppData/Local/Temp/Rtmpy6Dw9o/Rinst38382c4e468d/00LOCK-luna/00new/luna/libs/x64
   ** R
   ** inst
   ** byte-compile and prepare package for lazy loading
   Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
     namespace 'terra' 1.4-22 is being loaded, but >= 1.5.3 is required
   Calls: <Anonymous> ... withCallingHandlers -> loadNamespace -> namespaceImport -> loadNamespace
   Execution halted
   ERROR: lazy loading failed for package 'luna'
-  removing 'C:/Users/admin/AppData/Local/Temp/Rtmpy6Dw9o/Rinst38382c4e468d/luna'
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'luna' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout & stderr were printed`

**Comment by carolkimani** [comment]
I think this one works...

`> install.packages('luna', repos='https://rspatial.r-universe.dev')
also installing the dependency ‘terra’

trying URL 'https://rspatial.r-universe.dev/bin/windows/contrib/4.1/terra_1.5-7.zip'
Content type 'application/zip' length 41684071 bytes (39.8 MB)
downloaded 39.8 MB

trying URL 'https://rspatial.r-universe.dev/bin/windows/contrib/4.1/luna_0.3-3.zip'
Content type 'application/zip' length 555309 bytes (542 KB)
downloaded 542 KB

package ‘terra’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  cannot remove prior installation of package ‘terra’
Warning in install.packages :
  problem copying F:\Folders\Programs\R-4.1.2\library\00LOCK\terra\libs\x64\terra.dll to F:\Folders\Programs\R-4.1.2\library\terra\libs\x64\terra.dll: Permission denied
Warning in install.packages :
  restored ‘terra’
package ‘luna’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\admin\AppData\Local\Temp\RtmpuU4ooe\downloaded_packages`

**Comment by rhijmans** [comment]
Great. You cannot install a package that is already loaded (as was the case with terra) but since you already had the correct version it did not matter.
