### ISSUE TITLE
GetNASA downloads empty hdf files

### ISSUE THREAD

**Issue by SoleHeredia** [rspatial/luna#32]
Hi, I tried to download MOD09A1 files using getNASA. I only got files of 27bytes and cannot read it with rast() from terra. However, if I download the same file from website they are bigger and I can read it with terra. I followed the steps from https://rspatial.org/modis/modis.pdf.
Could anyone help me?

**Comment by taylorheadland** [comment]
I am having the same issue too using MCD12Q1, cannot read the files in with terra and files only 27b large. @rhijmans

**Comment by Louis-Backstrom** [comment]
Same issue here. I believe this is a new issue - I have a script that worked back in February that no longer downloads files, best I can tell.

**Comment by lysoifer** [comment]
I am having the same issue using R 4.4.0. However, downloads work correctly in R 4.3.3

**Comment by ivazrod** [comment]
I am having the same issue too using R 4.4.1

**Comment by chamoisrouge** [comment]
Dear Luna team,

I have the same issues with empty files. Some months age my code worked pretty well but it does not work anymore... Someone spoke about configuring a netrc file but I really do not understand. Has someone a solution please? Thanks in advance.

**Comment by lerch-a** [comment]
I have the same issue. But I figured out the issue and found a temporary workaround.

The issue is that the authentification is not working with getNASA.

Workaround: Use the hidden function to get the urls, then go to your browser and copy & paste the individual urls.
results <- luna:::.searchGranules(product = product, start_date = start, end_date = end, extent = aoi, limit = 1e+05)
extract the "Online Access URLs"
urls <- unique(results[, "Online Access URLs"])

**Comment by chamoisrouge** [comment]
Thank you for the answer. On my side, finally I download the images using a Unix script with the wget function. It's a pitty it does not work anymore.

All the best

**Comment by rhijmans** [comment]
Sorry for the very long wait, but this works again, I think.

**Comment by elweiser** [comment]
I just ran into this problem, saw this thread, reinstalled luna, and indeed it now works. Thank you!

**Comment by RishiKowalski** [comment]
Same issue, occurring now with w/ Luna v.03-7, terra 1.8-98, GDAL 3.8.5 and R v4.5.2 for product = MCD12Q1. Any ideas on a fix? 

Trying the .searchGranules() workaround also failing for me as well.

**Comment by RishiKowalski** [comment]
Any update on this?

**Comment by lerch-a** [comment]
Sometime it is working fine. And a couple of weeks later its not working.
Just make sure you use the latest version and that the authentification is working successfully.

**Comment by RishiKowalski** [comment]
Is this on the NASA side? What explains the discrepant behavior for success on using .searchGranules() vs getNASA? Only asking as I'm encountering a use case (large area + multi-year) where opening and downloading 1k+ links isn't quite feasible.
